# config yaml

general:

bitget_api:
  url: "https://api.bitget.com"
  endpoints:
    historical_data: "/api/v2/spot/market/history-candles"
  limit: 20

data:
  symbol: "BTCUSDT"
  granularity: "1h"
  limit: 200  

deribit_api:
  get_instruments: "https://history.deribit.com/api/v2/public/get_instruments"
  get_trades: "https://history.deribit.com/api/v2/public/get_last_trades_by_instrument_and_time"